# Generated by Django 3.1.3 on 2020-11-18 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillar',
            name='capacity',
        ),
        migrations.AddField(
            model_name='pillar',
            name='user_pillar',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
