# Generated by Django 3.1.3 on 2020-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'pillar_head'), (2, 'normal-user'), (3, 'management_user')], default=2, null=True),
        ),
    ]
