# Generated by Django 3.1.3 on 2020-11-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201117_1320'),
        ('account', '0003_auto_20201116_1338'),
    ]

    operations = [
    ]
