# Generated by Django 3.1.3 on 2020-11-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Activity Name')),
                ('Participants_number', models.IntegerField()),
                ('Start_time', models.DateTimeField(verbose_name='Start Date')),
                ('End_time', models.DateTimeField(verbose_name='End Date')),
                ('program_desc', models.TextField(blank=True, max_length=500, verbose_name='Activity Description')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Venue Name')),
                ('location', models.CharField(max_length=50)),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Program or Project Name')),
                ('program_desc', models.TextField(blank=True, max_length=500, verbose_name='Program Description')),
                ('Pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_Program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.venue'),
        ),
    ]
