# Generated by Django 3.1.6 on 2021-04-07 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dlab', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Activity Name')),
                ('type_of_activity', models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Round Table', 'Round Table'), ('Training', 'Training')], max_length=20)),
                ('Participants_number', models.IntegerField(verbose_name='Number Of Participants')),
                ('Start_time', models.DateField(verbose_name='Start Date')),
                ('End_time', models.DateField(verbose_name='End Date')),
                ('program_desc', models.TextField(blank=True, max_length=500, verbose_name='Activity Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Venue Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.location')),
            ],
            options={
                'verbose_name_plural': 'Venues List',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.venue_detail')),
            ],
            options={
                'verbose_name_plural': 'Venue Usage',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Program or Project Name')),
                ('program_desc', models.TextField(blank=True, max_length=500, verbose_name='Program Description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('Pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pillar')),
            ],
            options={
                'verbose_name_plural': 'Programs & Projects',
                'ordering': ('-date_modified',),
            },
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlab.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlab.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50, verbose_name='Collaboration Role')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('collaborator_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dlab.staff')),
                ('collaborator_name_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dlab.organization')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_Program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='Program/Project Name'),
        ),
    ]
