# Generated by Django 3.1.3 on 2020-12-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('dlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Activity Name')),
                ('type_of_activity', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Workshop'), (2, 'Round Table'), (1, 'Training')])),
                ('Participants_number', models.IntegerField(verbose_name='Number Of Participants')),
                ('Start_time', models.DateField(verbose_name='Start Date')),
                ('End_time', models.DateField(verbose_name='End Date')),
                ('program_desc', models.TextField(blank=True, max_length=500, verbose_name='Activity Description')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Venue Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.location')),
            ],
            options={
                'verbose_name_plural': 'Venue',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.DateTimeField()),
                ('End_time', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.venue_detail')),
            ],
            options={
                'verbose_name_plural': 'Venue Usage',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Program or Project Name')),
                ('program_desc', models.TextField(blank=True, max_length=500, verbose_name='Program Description')),
                ('Pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlab.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlab.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50, verbose_name='Collaboration Role')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('collaborator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlab.staff')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_Program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program', verbose_name='Program/Project Name'),
        ),
    ]
