# Generated by Django 3.1.3 on 2021-01-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlab', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='collaborator_name_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dlab.organization'),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='collaborator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dlab.staff'),
        ),
    ]
