# Generated by Django 3.1.3 on 2020-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='End_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='Start_time',
            field=models.DateTimeField(),
        ),
    ]
