# Generated by Django 3.1.3 on 2020-12-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name_plural': 'Programs And Projects'},
        ),
        migrations.AlterModelOptions(
            name='venue_detail',
            options={'verbose_name_plural': 'Venues'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='type_of_activity',
            field=models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Round Table', 'Round Table'), ('Training', 'Training')], max_length=20),
        ),
    ]
