# Generated by Django 3.1.3 on 2020-12-23 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documentation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('path', models.CharField(blank=True, max_length=2048)),
                ('slug', models.SlugField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.folder')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_type', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Images'), (2, 'Video'), (1, 'Documents')])),
                ('dete_uploaded', models.DateTimeField(auto_now_add=True)),
                ('upload_path', models.FileField(default='pillar/', upload_to=documentation.models.Folder.get_path, verbose_name='Choose File')),
                ('activity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.folder')),
                ('uploader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentations',
            },
        ),
    ]
