# Generated by Django 3.1.3 on 2020-12-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='upload_path',
            field=models.FileField(default='pillar/', upload_to='folder.get_path()', verbose_name='Choose File'),
        ),
    ]
