# Generated by Django 3.1.3 on 2021-01-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='activity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.activity'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='activity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.activity'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.folder'),
        ),
    ]
