# Generated by Django 3.1.6 on 2021-04-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20210407_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='os_file',
        ),
    ]
