# Generated by Django 3.1.3 on 2020-11-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Organization Name')),
                ('Address', models.CharField(max_length=50)),
                ('Telephone_number', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50, verbose_name='Collaboration Role')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.activity')),
                ('collaborator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlab.organization')),
            ],
        ),
    ]
