# Generated by Django 3.1.3 on 2020-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlab', '0002_auto_20201128_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='organization',
        ),
        migrations.AddField(
            model_name='staff',
            name='organization',
            field=models.ManyToManyField(related_name='organization', to='dlab.Organization', verbose_name='Organization'),
        ),
    ]
