# Generated by Django 3.1.3 on 2020-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlab', '0003_auto_20201130_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ManyToManyField(related_name='staff', to='dlab.Organization', verbose_name='Organization'),
        ),
    ]
